/** Motivational quotes shown on the dashboard's Daily Wisdom card. */
export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  { text: 'You have power over your mind, not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius' },
  { text: 'The first and greatest victory is to conquer yourself.', author: 'Plato' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'We suffer more in imagination than in reality.', author: 'Seneca' },
  { text: 'He who conquers himself is the mightiest warrior.', author: 'Confucius' },
  { text: 'Difficulties strengthen the mind, as labor does the body.', author: 'Seneca' },
  { text: 'What we do in life echoes in eternity.', author: 'Marcus Aurelius' },
  { text: 'The successful warrior is the average man with laser-like focus.', author: 'Bruce Lee' },
  { text: 'We become what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Aristotle' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'If it is not right, do not do it; if it is not true, do not say it.', author: 'Marcus Aurelius' },
  { text: 'Self-control is the chief element in self-respect, and self-respect is the chief element in courage.', author: 'Thucydides' },
  { text: 'The cave you fear to enter holds the treasure you seek.', author: 'Joseph Campbell' },
  { text: 'Real freedom is not freedom from responsibility: it is the freedom that comes from mastering yourself.', author: '' },
  { text: 'Waste no more time arguing what a good man should be. Be one.', author: 'Marcus Aurelius' },
  { text: 'The more you sweat in training, the less you bleed in battle.', author: 'Sun Tzu' },
  { text: 'One day or day one. You decide.', author: '' },
  { text: 'Every battle is won before it is ever fought.', author: 'Sun Tzu' },
  { text: 'Between stimulus and response there is a space. In that space is our power to choose our response.', author: 'Viktor Frankl' },
  { text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'Marcus Aurelius' },
  { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
  { text: 'Your future self is watching you right now through your memories. Make him proud.', author: '' },
  { text: 'No man is free who is not master of himself.', author: 'Epictetus' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'The secret of discipline is motivation. When a man is sufficiently motivated, discipline will take care of itself.', author: 'Sir Alexander Paterson' },
  { text: 'We must all suffer one of two things: the pain of discipline or the pain of regret.', author: 'Jim Rohn' },
  { text: 'Either you run the day, or the day runs you.', author: 'Jim Rohn' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius' },
  { text: 'Pain is temporary. Quitting lasts forever.', author: 'Lance Armstrong' },
  { text: 'Do not pray for an easy life. Pray for the strength to endure a difficult one.', author: 'Bruce Lee' },
  { text: 'What you resist, persists. What you accept, you can change.', author: 'Carl Jung' },
  { text: 'Until you make the unconscious conscious, it will direct your life and you will call it fate.', author: 'Carl Jung' },
  { text: 'An unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.', author: 'Aristotle' },
  { text: 'The energy you put into controlling yourself is the same energy others waste on excuses.', author: '' },
  { text: 'Every day is a new opportunity to be better than yesterday.', author: '' },
  { text: 'The strongest man is not he who overcomes others, but he who overcomes himself.', author: '' },
  { text: 'A warrior does not give up what he loves. He finds the love in what he does.', author: 'Dan Millman' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'If you are going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'Continuous effort, not strength or intelligence, is the key to unlocking our potential.', author: 'Winston Churchill' },
  { text: 'In the middle of every difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb' },
  { text: 'Your life does not get better by chance. It gets better by change.', author: 'Jim Rohn' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
  { text: 'By failing to prepare, you are preparing to fail.', author: 'Benjamin Franklin' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },

  // ── Stoic philosophy ──
  { text: 'Make the best use of what is in your power, and take the rest as it happens.', author: 'Epictetus' },
  { text: 'It is not the man who has too little, but the man who craves more, that is poor.', author: 'Seneca' },
  { text: 'How long are you going to wait before you demand the best for yourself?', author: 'Epictetus' },
  { text: 'Wealth consists not in having great possessions, but in having few wants.', author: 'Epictetus' },
  { text: 'First say to yourself what you would be, and then do what you have to do.', author: 'Epictetus' },
  { text: 'The whole future lies in uncertainty: live immediately.', author: 'Seneca' },
  { text: 'Confine yourself to the present.', author: 'Marcus Aurelius' },
  { text: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', author: 'Marcus Aurelius' },
  { text: 'No man is free who is a slave to his own appetites.', author: 'Seneca' },
  { text: 'Man conquers the world by conquering himself.', author: 'Zeno of Citium' },
  { text: 'Freedom is the only worthy goal in life, won by disregarding things that lie beyond our control.', author: 'Epictetus' },
  { text: 'The greater the difficulty, the more glory in surmounting it.', author: 'Epictetus' },
  { text: 'It is in your power to retire into yourself whenever you choose.', author: 'Marcus Aurelius' },
  { text: 'A gem cannot be polished without friction, nor a man perfected without trials.', author: 'Seneca' },
  { text: 'To bear trials with a calm mind robs misfortune of its strength.', author: 'Seneca' },
  { text: 'The mind that is anxious about future events is miserable.', author: 'Seneca' },
  { text: 'Begin at once to live, and count each separate day as a separate life.', author: 'Seneca' },
  { text: 'He suffers more than necessary who suffers before it is necessary.', author: 'Seneca' },
  { text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca' },
  { text: 'While we wait for life, life passes.', author: 'Seneca' },
  { text: 'Sometimes even to live is an act of courage.', author: 'Seneca' },
  { text: 'True happiness is to enjoy the present, without anxious dependence upon the future.', author: 'Seneca' },
  { text: 'He is most powerful who has power over himself.', author: 'Seneca' },
  { text: 'Every new beginning comes from some other beginning\'s end.', author: 'Seneca' },
  { text: 'It is not that we have a short time to live, but that we waste a great deal of it.', author: 'Seneca' },
  { text: 'As long as you live, keep learning how to live.', author: 'Seneca' },
  { text: 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.', author: 'Marcus Aurelius' },
  { text: 'If it is endurable, then endure it. Stop complaining.', author: 'Marcus Aurelius' },
  { text: 'Waste no time arguing about what a good man should be; just be one.', author: 'Marcus Aurelius' },
  { text: 'Don\'t explain your philosophy. Embody it.', author: 'Epictetus' },
  { text: 'Circumstances don\'t make the man, they only reveal him to himself.', author: 'Epictetus' },
  { text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle' },

  // ── Mental toughness & grit ──
  { text: 'Suffering is temporary, but giving up lasts forever.', author: '' },
  { text: 'You don\'t have to be extreme, just consistent.', author: '' },
  { text: 'The pain of discipline weighs ounces. The pain of regret weighs tons.', author: '' },
  { text: 'Calluses don\'t form on comfort.', author: '' },
  { text: 'Comfort is the enemy of progress.', author: 'P.T. Barnum' },
  { text: 'A man who conquers himself is greater than one who conquers a thousand battles.', author: 'Buddha' },
  { text: 'It is not the mountain we conquer, but ourselves.', author: 'Edmund Hillary' },
  { text: 'The body achieves what the mind believes.', author: '' },
  { text: 'You will never always be motivated, so you must learn to be disciplined.', author: '' },
  { text: 'Hard choices, easy life. Easy choices, hard life.', author: 'Jerzy Gregorek' },
  { text: 'The cave you most want to avoid entering holds the treasure you seek.', author: '' },
  { text: 'Stay hard.', author: 'David Goggins' },
  { text: 'Most people quit not because of the pain, but because they cannot see the finish line.', author: '' },
  { text: 'Nobody cares, work harder.', author: 'David Goggins' },
  { text: 'You are in danger of living a life so comfortable that you will die without ever realizing your true potential.', author: 'David Goggins' },
  { text: 'When you think you\'re done, you\'re only at 40% of your true capability.', author: 'David Goggins' },
  { text: 'The mind always fails first, not the body.', author: 'David Goggins' },
  { text: 'Suffer the pain of discipline or suffer the pain of disappointment.', author: '' },
  { text: 'Rock bottom became the solid foundation on which I rebuilt my life.', author: 'J.K. Rowling' },
  { text: 'What stands in the way becomes the way.', author: 'Marcus Aurelius' },
  { text: 'The obstacle is the path.', author: 'Zen Proverb' },
  { text: 'A river cuts through rock not because of its power, but because of its persistence.', author: 'Jim Watkins' },
  { text: 'Endurance is one of the most difficult disciplines, but it is to the one who endures that the final victory comes.', author: 'Buddha' },
  { text: 'The struggle you are in today is developing the strength you need for tomorrow.', author: 'Robert Tew' },
  { text: 'Tough times never last, but tough people do.', author: 'Robert H. Schuller' },

  // ── Self-discipline & habit ──
  { text: 'Motivation gets you started. Discipline keeps you going.', author: 'Jim Ryun' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln' },
  { text: 'We are what we repeatedly do.', author: 'Will Durant' },
  { text: 'Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.', author: 'John C. Maxwell' },
  { text: 'Discipline is the soul of an army. It makes small numbers formidable.', author: 'George Washington' },
  { text: 'He who would govern others must first master himself.', author: 'Philip Massinger' },
  { text: 'You cannot escape the responsibility of tomorrow by evading it today.', author: 'Abraham Lincoln' },
  { text: 'Order your soul. Reduce your wants.', author: 'Ezra Pound' },
  { text: 'A man without self-control is like a city broken into and left without walls.', author: 'Proverbs' },
  { text: 'It is easier to prevent bad habits than to break them.', author: 'Benjamin Franklin' },
  { text: 'You will never change your life until you change something you do daily.', author: 'Mike Murdock' },
  { text: 'Self-discipline is the magic power that makes you virtually unstoppable.', author: 'Dan Kennedy' },
  { text: 'The successful man is the one who has the discipline to stop seeking distraction.', author: '' },
  { text: 'Discipline weighs ounces, regret weighs tons.', author: '' },
  { text: 'Set your goals high, and don\'t stop till you get there.', author: 'Bo Jackson' },
  { text: 'The chains of habit are too weak to be felt until they are too strong to be broken.', author: 'Samuel Johnson' },
  { text: 'What you do every day matters more than what you do once in a while.', author: 'Gretchen Rubin' },
  { text: 'Master your habits, master your life.', author: '' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },

  // ── Resilience & transformation ──
  { text: 'It is during our darkest moments that we must focus to see the light.', author: 'Aristotle' },
  { text: 'Out of suffering have emerged the strongest souls.', author: 'Khalil Gibran' },
  { text: 'The wound is the place where the light enters you.', author: 'Rumi' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'The flower that blooms in adversity is the rarest and most beautiful of all.', author: '' },
  { text: 'You were given this life because you are strong enough to live it.', author: '' },
  { text: 'Rock bottom is a solid place to build from.', author: '' },
  { text: 'Every storm runs out of rain.', author: 'Maya Angelou' },
  { text: 'I learned that courage was not the absence of fear, but the triumph over it.', author: 'Nelson Mandela' },
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'There is no growth without discomfort.', author: '' },
  { text: 'What does not kill me makes me stronger.', author: 'Friedrich Nietzsche' },
  { text: 'You are stronger than you think and more capable than you ever imagined.', author: '' },
  { text: 'A diamond is just a piece of coal that handled stress exceptionally well.', author: 'Henry Ford' },
  { text: 'The phoenix must burn to emerge.', author: 'Janet Fitch' },
  { text: 'Healing is not linear, but every step forward counts.', author: '' },
  { text: 'You cannot calm the storm, so stop trying. What you can do is calm yourself, the storm will pass.', author: 'Timber Hawkeye' },
  { text: 'Sometimes you don\'t realize your own strength until you face your own challenges.', author: '' },
  { text: 'Scar tissue is stronger than the skin it replaces.', author: '' },

  // ── Action, focus & purpose ──
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'Knowing yourself is the beginning of all wisdom; controlling yourself is the end of it.', author: '' },
  { text: 'Where focus goes, energy flows.', author: 'Tony Robbins' },
  { text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee' },
  { text: 'Concentrate all your thoughts upon the work at hand.', author: 'Alexander Graham Bell' },
  { text: 'You are not your urges. You are the one who notices them.', author: '' },
  { text: 'The urge will pass whether you act on it or not. Choose not to.', author: '' },
  { text: 'Energy flows where attention goes. Direct yours with intention.', author: '' },
  { text: 'He who has a strong enough why can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'Vision without action is merely a dream.', author: 'Joel Barker' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'A man who has no purpose in life will be aimless in his actions.', author: '' },
  { text: 'Purpose is the engine, discipline is the fuel.', author: '' },
  { text: 'The man who has no inner life is the slave of his surroundings.', author: 'Henri-Frédéric Amiel' },

  // ── Identity & inner mastery ──
  { text: 'You become what you give your attention to.', author: 'Epictetus' },
  { text: 'The man who can master his own desires is more powerful than one who masters armies.', author: '' },
  { text: 'A man\'s real possession is his power of self-control.', author: '' },
  { text: 'Govern your passions, or they will govern you.', author: 'Horace' },
  { text: 'He who reigns within himself, and rules his passions, desires, and fears, is more than a king.', author: 'John Milton' },
  { text: 'Sow a thought, reap an act. Sow an act, reap a habit. Sow a habit, reap a character. Sow a character, reap a destiny.', author: '' },
  { text: 'A man is but the product of his thoughts. What he thinks, he becomes.', author: 'Mahatma Gandhi' },
  { text: 'The first step to becoming the man you want to be is deciding who that man is.', author: '' },
  { text: 'Self-mastery is the gateway to all other forms of mastery.', author: '' },
  { text: 'The man who has conquered his own mind has conquered the world.', author: '' },
  { text: 'Build the version of yourself your future depends on.', author: '' },
  { text: 'Every day you say no to your old self, you say yes to the man you are becoming.', author: '' },
  { text: 'Who you are tomorrow begins with what you choose today.', author: '' },
  { text: 'Discipline is the highest form of self-love.', author: '' },
  { text: 'The strongest people are not those who show strength in front of others, but those who fight battles unseen.', author: '' },

  // ── Time, patience & long-term thinking ──
  { text: 'Patience is bitter, but its fruit is sweet.', author: 'Jean-Jacques Rousseau' },
  { text: 'Good things come to those who wait, better things come to those who work for them.', author: '' },
  { text: 'The bamboo that bends is stronger than the oak that resists.', author: 'Japanese Proverb' },
  { text: 'Great things take time. Trust the process.', author: '' },
  { text: 'Slow progress is still progress.', author: '' },
  { text: 'The two most powerful words when facing temptation are: not yet.', author: '' },
  { text: 'A delay is not a denial.', author: '' },
  { text: 'Time is the wisest counselor of all.', author: 'Pericles' },
  // ── NoFap & recovery specific (original) ──
  { text: 'You are not broken. You are healing.', author: '' },
  { text: 'Every clean day rewires a little more of you.', author: '' },
  { text: 'Discomfort now is freedom later.', author: '' },
  { text: 'The version of you that gives in is not the real you, it\'s the conditioned you.', author: '' },
  { text: 'Cravings are temporary weather, not your permanent climate.', author: '' },
  { text: 'You don\'t need willpower forever, just for the next ten minutes.', author: '' },
  { text: 'Each day clean is a brick in a wall nothing can knock down.', author: '' },
  { text: 'The urge is loud, but it is not in charge.', author: '' },
  { text: 'Relapse is not the end of the story, it is a single sentence in a much longer book.', author: '' },
  { text: 'Your future self is being built right now, one choice at a time.', author: '' },
  { text: 'You are training a muscle no one else can see, and it is the most important one you have.', author: '' },
  { text: 'The man on day 100 was once on day 1. Keep going.', author: '' },
  { text: 'Freedom feels like boredom at first. Stay anyway.', author: '' },
  { text: 'Nobody is coming to save you, but you are fully capable of saving yourself.', author: '' },
  { text: 'The flatline ends. The clarity does not.', author: '' },
];

/** Pick a random quote index, avoiding an immediate repeat. */
export function randomQuoteIndex(exclude: number): number {
  let next: number;
  do { next = Math.floor(Math.random() * QUOTES.length); }
  while (next === exclude && QUOTES.length > 1);
  return next;
}
